import {
  SiHtml5,
  SiCss3,
  SiJavascript,
  SiTypescript,
  SiPython,
  SiC,
  SiCplusplus,
  SiPhp,
  SiRuby,
  SiGo,
  SiSwift,
  SiKotlin,
  SiRust,
  SiMysql,
  SiR,
  SiLinux,
  SiReact,
  SiAngular,
  SiSvelte,
  SiNextdotjs,
  SiTailwindcss,
  SiBootstrap,
  SiNodedotjs,
  SiExpress,
  SiDjango,
  SiFlask,
  SiSpringboot,
  SiRubyonrails,
  SiLaravel,
  SiFlutter,
  SiIonic,
  SiTensorflow,
  SiPytorch,
  SiElectron,
} from "react-icons/si";

// Language Icons Mapping
export const languageIcons = {
  HTML: SiHtml5,
  CSS: SiCss3,
  JavaScript: SiJavascript,
  TypeScript: SiTypescript,
  Python: SiPython,
  C: SiC,
  "C++": SiCplusplus,
  PHP: SiPhp,
  Ruby: SiRuby,
  Go: SiGo,
  Swift: SiSwift,
  Kotlin: SiKotlin,
  Rust: SiRust,
  SQL: SiMysql, // MySQL als Platzhalter für SQL
  R: SiR,
  Shell: SiLinux, // Linux Icon als Platzhalter für Shell
};

// Framework Icons Mapping
export const frameworkIcons = {
  React: SiReact,
  Angular: SiAngular,
  Svelte: SiSvelte,
  "Next.js": SiNextdotjs,
  "Tailwind CSS": SiTailwindcss,
  Bootstrap: SiBootstrap,
  "Node.js": SiNodedotjs,
  Express: SiExpress,
  Django: SiDjango,
  Flask: SiFlask,
  "Spring Boot": SiSpringboot,
  "Ruby on Rails": SiRubyonrails,
  Laravel: SiLaravel,
  Flutter: SiFlutter,
  Ionic: SiIonic,
  TensorFlow: SiTensorflow,
  PyTorch: SiPytorch,
  Electron: SiElectron,
};

export const languages = [
  "HTML",
  "CSS",
  "JavaScript",
  "TypeScript",
  "Python",
  "C",
  "C++",
  "PHP",
  "Ruby",
  "Go",
  "Swift",
  "Kotlin",
  "Rust",
  "SQL",
  "R",
  "Shell",
];

export const frameworks = [
  "React",
  "Angular",
  "Svelte",
  "Next.js",
  "Tailwind CSS",
  "Bootstrap",
  "Node.js",
  "Express",
  "Django",
  "Flask",
  "Spring Boot",
  "Ruby on Rails",
  "Laravel",
  "Flutter",
  "Ionic",
  "TensorFlow",
  "PyTorch",
  "Electron",
];
